2017-10-20 16:22:12.303 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:24:04.853 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:27:59.697 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:29:19.986 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:34:36.674 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:53:54.674 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:54:05.530 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:54:23.062 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-20 16:55:12.715 [error] <0.318.0>@xprof_tracer:monitor:43 syntax error before:  at column 6
2017-10-23 10:48:33.528 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 10:49:52.487 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 10:55:04.636 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 10:55:22.452 [error] emulator Error in process <0.317.0> with exit value:
{{badarity,{#Fun<Elixir.Hello.0.18853651>,[1]}},[{'Elixir.Enum','-each/2-fun-0-',3,[{file,"lib/enum.ex"},{line,681}]},{'Elixir.Enum',reduce_range_inc,4,[{file,"lib/enum.ex"},{line,1856}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,1831}]}]}
2017-10-23 10:55:33.745 [error] emulator Error in process <0.320.0> with exit value:
{{badarity,{#Fun<Elixir.Hello.0.18853651>,[1]}},[{'Elixir.Enum','-each/2-fun-0-',3,[{file,"lib/enum.ex"},{line,681}]},{'Elixir.Enum',reduce_range_inc,4,[{file,"lib/enum.ex"},{line,1856}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,1831}]}]}
2017-10-23 10:56:01.325 [error] emulator Error in process <0.323.0> with exit value:
{undef,[{'Elixir.Hello',hello,[<<"BOSS">>],[]}]}
2017-10-23 10:56:11.401 [error] emulator Error in process <0.330.0> with exit value:
{{badarity,{#Fun<Elixir.Hello.0.18853651>,[1]}},[{'Elixir.Enum','-each/2-fun-0-',3,[{file,"lib/enum.ex"},{line,681}]},{'Elixir.Enum',reduce_range_inc,4,[{file,"lib/enum.ex"},{line,1856}]},{'Elixir.Enum',each,2,[{file,"lib/enum.ex"},{line,1831}]}]}
2017-10-23 10:57:57.868 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 11:00:06.651 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 11:01:29.416 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
2017-10-23 11:04:14.878 [error] <0.155.0> Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{true,false,500}}) at <0.160.0> exit with reason normal in context child_terminated
